name: AMP3-Spring-2026-Project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - ipython
  - scipy
  - scikit-learn
  - pip:
    - torch
    - allensdk